### ISSUE TITLE
Clips4sale is broken

### ISSUE THREAD

**Issue by user237890** [ThePornDatabase/ThePornDB.bundle#10]
Hello there! Awesome work, this is super helpful.

I've been trying to organise some clips from Clips4sale and I have the Title Format set to the default `{actors} - {title} [{studio}/{series}]`, however the Actors name do not seem to be appearing. I am aware Clips4sale have been changing some of their website for the past year or so, so maybe something has been affected whilst doing so.

For example, outputs are returning ` - {title} [{studio}/{series}]`

Thanks for your time.

Edit: I just realised there's really no way of knowing the Actors names on Clips4sale, so maybe a better solution would be to just use the Studio name.

**Comment by Darklyter** [comment]
That's because there isn't a place for the performers to be listed on most of the Clips4Sale studios.  Is there one in particular that you're looking for? I tried to grab the performers where I could, but the vast majority of them would need to be manually entered per scene, which honestly isn't going to happen.  :-)

**Comment by user237890** [comment]
@Darklyter some studios that is already gathered is Xev Bellringer and Meana Wolf. Would be good to have those. However, then that introduces the issue of if there are multiple actors. Why not just have the Clips4sale studio name instead of the actor?

**Comment by Darklyter** [comment]
You lost me...  do you mean to attach Xev Bellringer to all of the scenes from that "studio"?  Same with Meana Wolf?  I can, and actually do with Mandy Flores, just hadn't at that point.

**Comment by user237890** [comment]
Yes, that'd be great!

My second part of that comment was suggesting to just simply at the Clips4sale studio name attached since there's no ways of determining who's in a scene.
