### ISSUE TITLE
dorcelClub provides descriptions in french rather than english

### ISSUE THREAD

**Issue by finkille** [ThePornDatabase/ThePornDB.bundle#12]
Titles are in English, however the description is in french.

Example:
https://metadataapi.net/scenes/dorcel-club-one-night-in-los-angeles-with-emily

Comparing to:

https://www.dorcelclub.com/en/scene/83589/one-night-in-los-angeles-with-emily

Seems to have started when the cookies ran out and was replaced by dynamic cookies, but could also be url-changes (notice the /en/ in the url path above)

**Comment by Darklyter** [comment]
Current PR fixes the problem, but hasn't been merged and updated to the site yet.  When it is we can rescrape to get the corrected info.  Until then nightly processes overwrite any changes made.

**Comment by finkille** [comment]
The PR you did was merged 19 days ago according to GitHub ( https://github.com/ThePornDatabase/scrapers/pull/97 ), and there seems to be no other open PRs? Or are we talking about separate repositories?
