### ISSUE TITLE
This scene is invisible to the scanner

### ISSUE THREAD

**Issue by WilliamsVM** [ThePornDatabase/ThePornDB.bundle#13]
https://metadataapi.net/scenes/everything-butt-anal-sluts-dakota-skye-casey-calvert-aiden-starr

I dutifully named this scene "Everything Butt - 2014-12-02 - Anal Sluts Dakota Skye, Casey Calvert, Aiden Starr". But alas. 

This scene is unsearchable. I'm not sure why but no combination of elements from the studio, date or title will give you that scene on Plex or in the scene search bar at https://metadataapi.net/scenes (I find that if I can get the title to work there, it will find it in plex as well).  :(

**Comment by DirtyRacer1337** [comment]
I don't see any problems, https://metadataapi.net/scenes?q=Everything+Butt+-+2014-12-02+-+Anal+Sluts+Dakota+Skye,+Casey+Calvert,+Aiden+Starr

**Comment by WilliamsVM** [comment]
hmm, still not finding it in Plex
![Capture](https://user-images.githubusercontent.com/40531925/156554165-c76f3b73-b294-4531-90a6-f388c430f18d.PNG)
