### ISSUE TITLE
Agent not showing up in Plex

### ISSUE THREAD

**Issue by hitthisnows** [ThePornDatabase/ThePornDB.bundle#17]
I shutdown Plex, downloaded the thePornDB.bundle, unzipped, and renamed it and placed it into my Plex plugin folder. When I restart Plex, the other agents show up, but not ThePornDB. Any ideas on debugging or what could be wrong?

Screenshot of plugins folder:
![image](https://user-images.githubusercontent.com/102377013/160168368-0c28155b-1550-44d7-b54e-8e62bfbcc172.png)

Screenshot of agents:
![image](https://user-images.githubusercontent.com/102377013/160168549-f43a1bfa-1539-4dfc-a871-d63501db5e26.png)

Thanks!

**Comment by Val223** [comment]
I've only just discovered this scraper and am discovering the same issue also.
