### ISSUE TITLE
No covers from metadataapi

### ISSUE THREAD

**Issue by rzitter** [ThePornDatabase/ThePornDB.bundle#28]
Hi, 

Ive installed the plugins in a new plex instance on a fresh installed Alma Linux 9. Everthing worked great for all metadata except the covers. 

I have created an API key with all permissions. 

Extra info:
With the default agents everything works perfect.

**Comment by DirtyRacer1337** [comment]
try now

**Comment by buehlech** [comment]
Hi,
I've the same problem. i get no covers from the tpdb agent. Metadata works well, but no covers.
I have created an API key with all permissions.
With the default agents everything works perfect.
