### ISSUE TITLE
Incorrect video detection

### ISSUE THREAD

**Issue by RickSan77** [ThePornDatabase/ThePornDB.bundle#32]
I am having a really low success in matching of videos to the correct metadata.  Files have been independently checked on the database to ensure they match correct dates and names.

Setup: 
Asustor NAS setup with Plex v 4.87.2 (webtools 3.0.0 also installed)

Folder hierarchy: 
/videos/studio/

Video naming format used: 
Studio YYYY-MM-DD Video Title.Extension

Library settings: 
Scanner (Plex Video Files Scanner), Agent (ThePornDB), API key entered, "Use Custom Title Format" selected, "Collections from Networks" selected, title format = "{studio} - {title}"

Agent settings: 
Movies -> ThePornDB
ThePornDB selected
Lamdba unselected
Local Media Assets (Movies) unselected

**Comment by Darklyter** [comment]
Are you using the "Scene" bundle?  The two subdirectories for Scenes and Movies are what you actually need to put into the plugins folder.  If you have 'ThePornDB.bundle' as a directory in that folder, remove it and restart Plex

**Comment by Darklyter** [comment]
By way of explanation, ThePornDB.bundle already existed as the project name when I brought it up to date and split out the movies.  I just used it as the 'container' for the _actual_ bundles.  Though it's a confusing filepath when you download it, I admit
