### ISSUE TITLE
MomPOV Scene Unmatched Despite Release Date Correct

### ISSUE THREAD

**Issue by dodecaphone** [ThePornDatabase/ThePornDB.bundle#34]
The release date on "MomPOV - Shelly (Blonde Cougar With Gigantic Tits)" has been confirmed by IAFD and multiple other sites as Oct 10, 2019 (2019-10-10). No title to that effect comes up on scene matching when the date is used. Two other MomPOV scenes appear on that date but this title is not pulling correctly.

**Comment by Darklyter** [comment]
It's because the name Shelly isn't attached to the scene on the site.  'mompov 2019-10-10 blonde cougar with gigantic tits' works fine.
You can always go to https://metadataapi.net/scenes in a browser and play with terms to find what you need, then just mirror that in Plex
