### ISSUE TITLE
What is the Proper Naming Convention for the scraper to automatically match?

### ISSUE THREAD

**Issue by adtdev20** [ThePornDatabase/ThePornDB.bundle#40]
This is for the Scene Scraper

Most of the content I have in Plex is formatted as:

```Studio/Series - YYYY-MM-DD - Actor Name - Scene Title```

However, the scraper doesn't seem to automatically match content named in this convention. Is there a way to properly format filenames while keeping the date available? Does the scraper take the date into account when matching?

**Comment by Darklyter** [comment]
Quite often the performer name will mess it up.  If they aren't attached to the scene, for example.   The easiest thing to do is go to https://metadataapi.net/scenes and just do a search for your filename (minus extension) to see if you get anything
