### ISSUE TITLE
Issues matching movies

### ISSUE THREAD

**Issue by TheEvilMonkey** [ThePornDatabase/ThePornDB.bundle#41]
Having a heck of a time getting movies to match properly.  As an example, I have a movie called "Haunted Hearts".  Filename is "Haunted Hearts.mp4".  Nothing else in the folder.

It never matches anything in TPDB.  I can find the movie at this URL:  https://api.metadataapi.net/movies/3f69af3e-619b-4205-b25f-16b423b98a95

Is this an issue on the TPDB side?  Ideally if I could just use the movie ID in Plex to match that would be helpful, but that doesn't appear to be an option like it is in Emby/JF.  Any other suggestions on better matching for movies?

**Comment by DirtyRacer1337** [comment]
logs

**Comment by TheEvilMonkey** [comment]
Assume this is what you want...not sure if there are more detailed logs I can enable?  You'll find the most recent search for "Haunted Hearts" at the end.
[com.plexapp.agents.theporndbmovies.log](https://github.com/ThePornDatabase/ThePornDB.bundle/files/10470916/com.plexapp.agents.theporndbmovies.log)

**Comment by DirtyRacer1337** [comment]
Disable use `Use Matching by OpenSubtitleHash`

**Comment by TheEvilMonkey** [comment]
Tried that with no luck.  However, what did work (for some dumb reason) is searching for "Haunted Heart" (without the 's' on the end).  Attached updated logs if it helps.
[com.plexapp.agents.theporndbmovies.log](https://github.com/ThePornDatabase/ThePornDB.bundle/files/10470947/com.plexapp.agents.theporndbmovies.log)

**Comment by DirtyRacer1337** [comment]
You not disable it, and add site name to file

**Comment by TheEvilMonkey** [comment]
I disabled the Hash matching option but looking in the logs it appears it is still searching by hash.   Tried a Plex restart as well, just to make sure.

I changed the filename to match exactly what it should be (I think):  Wicked.2014.05.05.Haunted.Hearts

2023-01-20 18:27:39,335 (3118) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': '3258af413f6e760b', 'name': 'Haunted Hearts', 'filename': 'H%3A%5CMedia%5CAdult%20Movies%5CHaunted%2EHearts%2EXXX%2E1080p%2EWEBRip%2Ex264-PAYiSO%5CWicked%2E2014%2E05%2E05%2EHaunted%2EHearts%2Emp4', 'source': 'web', 'plexHash': '046b087b2c285a695567399e95f65f77a1324caa', 'duration': '5546944', 'id': '233493'}

![image](https://user-images.githubusercontent.com/2296106/213829119-7728251f-68d5-440c-96a4-9ad478930383.png)

**Comment by TheEvilMonkey** [comment]
Finally got it to work.  Had to tell Plex to use Filename for search and ignore title in Plex.

**Comment by DirtyRacer1337** [comment]
You'll not believe but in agent setting there is option Use Filename for search
