### ISSUE TITLE
its not working now!

### ISSUE THREAD

**Issue by magic777** [ThePornDatabase/ThePornDB.bundle#47]
hello
Is there any update coz it's not working with the last plex update?

**Comment by Jafar412** [comment]
Same here , not working with the latest plex version

**Comment by NullKnox** [comment]
Anyone find a fix for this yet?

**Comment by Jafar412** [comment]
no fix atm , just downgrade it

**Comment by Gykes** [comment]
It's a plex issue with windows based installs, nothing we can do on our end. You just have to downgrade and wait for plex to push and update. I'm not aware of an ETA for it.
