### ISSUE TITLE
Pornstars portraits

### ISSUE THREAD

**Issue by Gnorkie** [ThePornDatabase/ThePornDB.bundle#48]
First of all, I'm using Plex. I've noticed that very often the pornstar image is a full body picture and it gets wrongly cropped when inserted in the scene/movie details, like... you see half of the face.
Is there a way to customise that? Is there a way to tell Plex and the agent which picture to use?

Sorry If this is a double post, I've searched but I couldn't find a similar request.

Cheers,
Stefano

**Comment by DirtyRacer1337** [comment]
it used dace field, just not always it can detect face
