### ISSUE TITLE
actor thumbs

### ISSUE THREAD

**Issue by drumdude65** [ThePornDatabase/ThePornDB.bundle#58]
Actor thumbs aren't working with newest agent and latest Plex update ver 1.40.0.7998 I tried downgrading Plex to 1.32.8.7639 Same result, matching works except actor thumb. I get a generic placeholder pic. If Actor is already existing in another clip, a match replaces good thumb with same generic placeholder. I did confirm these are performers with photos showing on Metadaatapi.net .

**Comment by DirtyRacer1337** [comment]
fixed
