### ISSUE TITLE
The PornDB Shutdown

### ISSUE THREAD

**Issue by mkwatchface** [ThePornDatabase/ThePornDB.bundle#59]
Hello,

ThepornDB has announced its shutdown since yesterday. What is the future of this bundle or any alternatives?

Thanks

**Comment by Darklyter** [comment]
We're working on bringing it back up.  Just keep an eye on the page or the discord [TPDB Discord](https://discord.gg/CvmFRAAw)

**Comment by mkwatchface** [comment]
> We're working on bringing it back up. Just keep an eye on the page or the discord [TPDB Discord](https://discord.gg/CvmFRAAw)

Thank you for your response! I am glad to hear that its gonna be back up!

**Comment by Tscherno** [comment]
Is the Discord channel removed as well? I can't access it.

**Comment by DirtyRacer1337** [comment]
Try this on, [Discord](https://discord.gg/XpSGpaB)

**Comment by DirtyRacer1337** [comment]
We back

**Comment by mkwatchface** [comment]
> We back

Hello, thanks for the information and i appreciate your hard work and fast solution! May i ask please, is there any action i need to take for it to work? Re-download maybe?

Currently it wasnt able to find any results when i scanned my library so apparently i did something wrong!

Please for some further help!

**Comment by DirtyRacer1337** [comment]
you need update plugin, we moved to new domain, join to our [Discord](https://theporndb.net/discord) for faster support
