### ISSUE TITLE
Matching Score

### ISSUE THREAD

**Issue by cookie050** [ThePornDatabase/ThePornDB.bundle#60]
Is there a way to change the minimal score to match?

**Comment by DirtyRacer1337** [comment]
that's question to plex devs

**Comment by cookie050** [comment]
found it in the code of the plugin 'Adult DVD Empire' changed the __init__.py and it works, so no it's not for the plex devs

**Comment by DirtyRacer1337** [comment]
can you link it?

**Comment by DirtyRacer1337** [comment]
![изображение](https://github.com/ThePornDatabase/ThePornDB.bundle/assets/17379553/7c696017-9146-4348-8d8b-bb474998d08a)
from their docs, never saw that it can be changed

**Comment by cookie050** [comment]
https://github.com/adultplexdev/AdultDVDEmpire.bundle/blob/master/Contents/Code/__init__.py

**Comment by DirtyRacer1337** [comment]
Should work absolutely the same, auto select still work with 85 or greater, doesn't see workaround it's even skip  item with score < 93
