### ISSUE TITLE
Not matching movies

### ISSUE THREAD

**Issue by magic777** [ThePornDatabase/ThePornDB.bundle#64]
I Rename the movie "actual name of the movie"
but nothing to show!

**Comment by DirtyRacer1337** [comment]
idk, works for me

**Comment by magic777** [comment]
For me not working,  I checked in theporndb same name and it exists 

![Recording2024-06-01034542-ezgif com-video-to-gif-converter](https://github.com/ThePornDatabase/ThePornDB.bundle/assets/26666472/d15c3789-39ea-4e85-82f4-9d0403eb9a91)
